# Generated by Django 5.2.5 on 2025-08-09 07:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="Jméno a příjmení"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E‑mail")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Telefon"),
                ),
                (
                    "street",
                    models.CharField(max_length=160, verbose_name="Ulice a č.p."),
                ),
                ("city", models.CharField(max_length=120, verbose_name="Město")),
                ("zip_code", models.CharField(max_length=20, verbose_name="PSČ")),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "shipping_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nová"),
                            ("paid", "Zaplaceno"),
                            ("shipped", "Odesláno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("shipping_method", models.CharField(blank=True, max_length=50)),
                ("pickup_provider", models.CharField(blank=True, max_length=50)),
                ("pickup_point_id", models.CharField(blank=True, max_length=100)),
                ("pickup_point_label", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
