# Generated by Django 5.2.5 on 2025-08-09 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pickup_point", "Výdejní místo"),
                            ("home_delivery", "Doručení na adresu"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("cod_supported", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("balikovna", "Balíkovna"),
                            ("zasilkovna", "Zásilkovna"),
                            ("ppl", "PPL"),
                            (None, "—"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cost_to_merchant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
