# Generated by Django 5.2.4 on 2025-08-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('delivery_method', models.CharField(choices=[('address', 'Doručení na adresu'), ('balikovna', 'Balíkovna')], max_length=20)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('balikovna_id', models.CharField(blank=True, max_length=255)),
                ('balikovna_code', models.CharField(blank=True, max_length=32)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'Nová'), ('paid', 'Zaplacená'), ('canceled', 'Zrušená'), ('shipped', 'Odeslaná'), ('done', 'Dokončená')], default='new', max_length=20)),
                ('carrier', models.CharField(choices=[('czp_balikovna', 'Česká pošta – Balíkovna'), ('czp', 'Česká pošta (ostatní)'), ('other', 'Jiný dopravce')], default='czp_balikovna', max_length=32)),
                ('tracking_code', models.CharField(blank=True, max_length=64)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
        ),
    ]
