# Generated by Django 5.2.5 on 2025-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ppl_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="ppl_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                choices=[
                    ("czp_balikovna", "Česká pošta – Balíkovna"),
                    ("czp", "Česká pošta (ostatní)"),
                    ("ppl", "PPL"),
                    ("other", "Jiný dopravce"),
                ],
                default="czp_balikovna",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("address", "Doručení na adresu"),
                    ("balikovna", "Balíkovna"),
                    ("ppl", "PPL Parcelshop"),
                ],
                max_length=20,
            ),
        ),
    ]
